name: Run with Environment Variables

on:
  push:
    branches: [ master ]

jobs:
  run-with-env:
    runs-on: ubuntu-latest
    needs: build-app-image  # This job depends on the previous workflow
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image (environment)
        run: docker build -t env-setter .  # Build the environment setting image

      - name: Run container with environment variables
        run: docker run -p 8050:8050 --name menu-management-container env-setter:latest registry.hub.docker.com/deborahf1999/restaurant-management-system:latest