name: Parse GitHub Secrets to Docker Image

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: menu-management-service/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: deborahf1999/restaurant-management-system:latest
          secrets: |
            "MONGO_DB_URI=${{ secrets.DB_URI }}"
            "ISSUER_URI=${{ secrets.ISSUER_URI }}"
          no-cache: true